require:
  - rubocop-faker
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Include:
    - '**/Rakefile'
    - '**/Gemfile'
    - '**/config.ru'
    - '**/*.rake'
    - '**/*.jbuilder'
    - '**/*.rb'
  Exclude:
    - '**/db/schema.rb'
    - '**/script/**/*'
    - '**/vendor/assets/**/*'
    - '**/bin/**/*'
    - '**/gems/**/*'
    - '**/node_modules/**/*'
    - '**/.bundle*/**/*'
Layout/LineLength:
  Max: 80
Lint/AmbiguousBlockAssociation:
  Enabled: false
Metrics/AbcSize:
  Max: 30
Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*'
    - '**/app/views/**/*.jbuilder'
    - '**/lib/**/*.rake'
    - '**/config/routes.rb'
    - '**/config/god*'
    - '**/db/seeds.rb'
    - '**/app/models/concerns/*'
    - '**/config/environments/*'
Metrics/ClassLength:
  Max: 150
Metrics/MethodLength:
  Max: 15
  Exclude:
    - '**/db/migrate/*'
Metrics/ModuleLength:
  Max: 150
Output:
  Exclude:
    - '**/db/seeds.rb'
    - '**/*.rake'
    - '**/rake_support.rb'
Naming/FileName:
  Exclude:
    - '**/Guardfile'
    - '**/Capfile'
Rails/UnknownEnv:
  Environments:
    - development
    - test
    - staging
    - production
RSpec/EmptyExampleGroup:
  Enabled: false
RSpec/ExampleLength:
  Max: 15
RSpec/NestedGroups:
  Max: 5
Style/BlockDelimiters:
  Enabled: false
Style/Documentation:
  Exclude:
    - '**/db/migrate/*'
Style/Lambda:
  Exclude:
    - 'app/models/**/*'
