version: '3'

services:
  redis:
    image: redis:latest

  adminer:
    image: adminer
    ports:
      - 9999:8080

  rails:
    build: .
    command: ./docker-entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/user/public_html:cached
      - .bash_history:/home/user/.bash_history
    depends_on:
      - redis

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/home/user/public_html:cached
    depends_on:
      - redis
