version: '3'

services:
  redis:
    image: redis:latest

  adminer:
    image: registry.roguepod.com/adminer:latest
    ports:
      - 9999:80

  rails:
    build: .
    command: bundle exec rails s -b 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - .:/home/user/public_html:cached
      - .bash_history:/home/user/.bash_history
    depends_on:
      - redis

  sidekiq:
    build: .
    command: bundle exec god -c config/god.rb --no-syslog -D
    volumes:
      - .:/home/user/public_html:cached
      - .bash_history:/home/user/.bash_history
    depends_on:
      - redis

  # webpack:
  #   build: .
  #   command: ./bin/webpack-dev-server
  #   volumes:
  #     - .:/home/user/public_html
  #   depends_on:
  #     - redis
